#!/usr/bin/env bash

## Install ansible
sudo apt-add-repository -y ppa:ansible/ansible
sudo add-apt-repository ppa:neovim-ppa/unstable -y
sudo apt-get update -y
sudo apt-get install -y curl git software-properties-common ansible

## pull ansible
sudo ansible-pull -K -J -U https://github.com/c00rni/ansible.git
