#!/usr/bin/env bash                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                     
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"                                                                                                                                                                                                             
dry="0"                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                     
while [[ $# -gt 0 ]]; do                                                                                                                                                                                                                                               
    if [[ "$1" == "--dry" ]]; then                                                                                                                                                                                                                                   
        dry="1"                                                                                                                                                                                                                                                      
    fi                                                                                                                                                                                                                                                               
    shift                                                                                                                                                                                                                                                            
done                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                     
log() {                                                                                                                                                                                                                                                              
    if [[ "$dry" == "1" ]]; then                                                                                                                                                                                                                                       
        echo "[DRY_RUN]: $@"                                                                                                                                                                                                                                         
    else                                                                                                                                                                                                                                                             
        echo "$@"                                                                                                                                                                                                                                                    
    fi                                                           
}                                                                

execute() {                                                      
    log "execute: $@"                                            
    if [[ "$dry" == "1" ]]; then                                   
        return                                                   
    fi                                                           

    "$@"                                                         
}                                                                
log "--------- dev-env ---------"

cd "$script_dir" || exit 1                                                   

copy_dir() {                                                     
    pushd "$1" || return                                                     
    local to="$2"                                                        
    # Using sed to cleanly strip out the leading "./" from find
    local dirs
    dirs=$(find . -maxdepth 1 -mindepth 1 -type d)

    for dir in $dirs; do                                         
        execute rm -rf "$to/$dir"                                  
        execute cp -r "$dir" "$to/$dir"
    done                                                         
    popd || return                                                         
}                                                                

copy_file() {                                                    
    local from="$1"                                                      
    local to="$2"                                                        
    local name
    name=$(basename "$from")                                       
    execute rm "$to/$name"                                         
    execute cp "$from" "$to/$name"                                   
}                                                                

export XDG_CONFIG_HOME="$HOME/.config"

# Creates the directory if it doesn't exist yet
mkdir -p "$XDG_CONFIG_HOME"

copy_dir .config "$XDG_CONFIG_HOME"
#copy_file .specialconfig "$HOME" 
