- hosts: localhost
  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
  pre_tasks:
    - name: Update cache
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags:
      - ssh 
      - dotfiles
      - zsh
  tasks:
  - import_tasks: tasks/zsh.yml
  - import_tasks: tasks/ssh.yml
  - import_tasks: tasks/dotfiles.yml
  - import_tasks: tasks/i3.yml
