# clone down the dotfiles and recurse the submodules (which are private)
- name: Cloning .dotfiles
  ansible.builtin.git:
    repo: 'git@github.com:c00rni/.dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: true
    update: true
    accept_hostkey: true
    version: main
  tags:
    - dotfiles
    - i3
- name: Install Stow
  become: true
  apt: name=stow
  tags:
    - dotfiles
    - install
    - i3
- name: Install zsh
  become: true
  apt: name=zsh
  tags:
    - dotfiles
    - install
    - zsh
- name: Stow dotfiles
  ansible.builtin.script:
    cmd: "{{ lookup('env', 'HOME') }}/.dotfiles/ubuntu"
  tags:
    - dotfiles
- name: Replace existing files
  shell: cd /home/corni/.dotfiles && git restore .
  tags:
    - dotfiles
    - i3
