#!/usr/bin/env bash

git clone -b v0.12.5 https://github.com/neovim/neovim.git $HOME/personal/neovim
sudo apt install -y cmake gettext lua5.3 liblua5.3-dev

cd $HOME/personal/neovim
make CMAKE_BUILD_TYPE=RelWithDebInfo
sudo make install
